### ISSUE TITLE
Staurolite: Filtered output moving to unfiltered when backed up

### ISSUE THREAD

**Issue by Ferlonas** [eirshy/Eirshy.DSP#16]
I have a few chemical plants making graphene and hydrogen from fire ice. The output runs to a splitter, which should move the graphene to a chest, the hydrogen to a tank. However, when the graphene is backed up because the chest is full, it is moved to the tank, which then causes the entire thing to block, even when the chest is emptied.

**Comment by eirshy** [comment]
I suspect you don't have the filter set correctly, as a chest on top of a splitter, with the splitter having a filter, provides both a filter and antifilter as appropriate.

If you're instead using a splitter to dispatch to a distant chest and tank, then you're running into the stated-in-the-readme change from vanilla where a splitter _without_ a chest on top of it does NOT provide an antifilter to the non-filtered outputs, as doing so would sacrifice a non-negligible amount of perf and is generally not necessary as most people run separate lines and use filters on the inserters themselves.

If you think this is still a bug, please describe your setup in a way I can reproduce it. Gonna leave this one open just in case.

**Comment by Ferlonas** [comment]
Ah, I guess then it's expected behaviour. I did not understand that line in the readme, but I guess that is the scenario.
I managed to work around by adding a second splitter for the unfiltered line, with the reverse setting.
What I still don't understand from the readme though is: What is a bunnyhop?

Thanks for the fast response. I guess this works as designed then and can be closed.

**Comment by eirshy** [comment]
A "Bunny Hop" is a rollercoaster term (at least, how I first learned it) for a really short hill.

If you try to build a belt across another belt, the belt pather automatically builds a bunny hop over the lower belt. Ergo, using splitters so two belts can cross without needing a full-size hill is no longer necessary.

You could always do bunny hops but prior to the pather automating them, you had to read the prologue section of the Tome of Belt Bending to manage it. Hence why I call them "canon" now- you don't have to abuse the system to get them any more.
