### ISSUE TITLE
VeinityProject + LazyOutposting Oil Collection Issue

### ISSUE THREAD

**Issue by MortisLegati** [eirshy/Eirshy.DSP#3]
With GiveDwarvesBuckets = true and GiveDwarvesHaulers = false, trying to place an Advanced Mining Machine atop a crude oil seep indicates that the miner needs resources.

**Comment by MortisLegati** [comment]
It works OK if GiveDwarvesHaulers = true, though; checks for oil seeps under the plate.

**Comment by eirshy** [comment]
Confirmed, issue was dwarves only noticed you bought them gear if haulers were included. Fix in the pipe already, expect it published before tomorrow =D
