### ISSUE TITLE
Ray Receiver Inventory not Optimised

### ISSUE THREAD

**Issue by Terrevil** [eirshy/Eirshy.DSP#4]
Please add option to adjust Ray Receiver Inventory size.

**Comment by eirshy** [comment]
Looking into it, will have to re-implement `PowerConsumerComponent`.`GameTick_Gamma`. Doable enough, though I'll have to double-check Jinx's work with More Megastructures to make sure I'm not gonna step on any toes with that.
Should get it done some point this weekend. Was originally planning tonight but the other pending issue was a legit bug (priority over a feature) and then I got distracted by something unrelated to DSP.

For future reference I don't really check the github as the project-wide readme notes; pinging me on the official discord's mod channel gets way faster results.

**Comment by eirshy** [comment]
Aight I lied on the "this weekend", then work decided to make me want to do non-coding things.
I've not forgotten about this, and I will get to it soon, promise.

**Comment by eirshy** [comment]
Update on this, I've got the base override done (untested), but there is a compat issue with JinxOAO's More Megastructures that I'll have to resolve before I can hit publish.

I'm including the ability to cheat a little and force 4-piling on output, as well as the ability to make catalysts pass-through for power-generation mode. As a sort of "while I'm here".

**Comment by eirshy** [comment]
Ah yeah good job me, write the code but don't publish it and then disappear for (almost) 7 months until Dark Fog.
It's a part of _Re_Buffer now (>0.2), I didn't bother with a MoreMegastructures compat fix since MoreMegastructures is currently broken.
