### ISSUE TITLE
Fuzzy and planet wide mining mess with advanced miners

### ISSUE THREAD

**Issue by Ryokeen1337** [eirshy/Eirshy.DSP#5]
As soon as either haulers or long picks are enabled the power scaling of advanced miners stops working. It's stuck at 100%
The UI bar still works, but the setting seems to be overriden somewhere.

**Comment by eirshy** [comment]
Yeah I noticed that too last night, Looking into it.

**Comment by eirshy** [comment]
Fixed, along with the vein not being shown and the fact that destroyed miner mk2s being rebuilt were probably disconnecting all their veins (I didn't look too closely as to what that was really loading for, just that its offset was wrong).
You can either fix your already-placed mk2s by reconstructing them, or you can use the on-save-load bugfixer option in the config for Lazy Outposting.
