### ISSUE TITLE
Funky Bug when trying to place pump on a sulfuric acid ocean planet

### ISSUE THREAD

**Issue by Lynserius** [eirshy/Eirshy.DSP#6]
![Screenshot 2023-12-22 205249](https://github.com/eirshy/Eirshy.DSP/assets/146405413/44179756-fe58-469a-80bf-26f01b0aa82e)

I'm pretty much illiterate when it comes to modding- but got a funky bug when trying to place a pump on a sulfuric acid planet. When I place one, the drone goes out and tries to build it, fails, and goes back, and tries again. But if I save and reload, it's placed properly (in a stack if it kept being placed), and doesn't output anything. Thought I'd report-

**Comment by VindictaUK** [comment]
Had the same issue when placing on water - bit of an annoyance as its happened before setting up water  or T3 tech on my new playthrough so now i cant get any H20 or progress any further

**Comment by eirshy** [comment]
I'm *pretty sure* this was fixed in v1.3.4, as that was when I fixed the miner swap code (`DwarvenContract` in the stack trace) running when placing water pumps.
I'm gonna tentatively close this under that assumption.
